package com.dheeraj.wallproai

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { WallProApp() } }
}

private val Bg=Color(0xFF08090D); private val Card=Color(0xFF12141C); private val Accent=Color(0xFF7C4DFF)

@Composable fun WallProApp() {
    var prompt by remember { mutableStateOf("") }
    var target by remember { mutableStateOf("Pixel 10") }
    var style by remember { mutableStateOf("Cinematic") }
    var generated by remember { mutableStateOf(false) }
    MaterialTheme(colorScheme=darkColorScheme(primary=Accent, background=Bg, surface=Card)) {
        Surface(Modifier.fillMaxSize(), color=Bg) {
            Column(Modifier.fillMaxSize().padding(20.dp), verticalArrangement=Arrangement.spacedBy(16.dp)) {
                Row(verticalAlignment=Alignment.CenterVertically) {
                    Text("WallPro", fontSize=30.sp, fontWeight=FontWeight.Bold); Text("-AI", fontSize=30.sp, fontWeight=FontWeight.Bold, color=Accent)
                }
                Text("Create wallpapers for any screen", color=Color.LightGray)
                OutlinedTextField(prompt, {prompt=it}, Modifier.fillMaxWidth().height(150.dp), label={Text("Describe your wallpaper")}, placeholder={Text("A futuristic neon city at night, rain, sports car...")}, shape=RoundedCornerShape(18.dp))
                Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) {
                    listOf("Pixel 10","Android TV","PC / Desktop","Custom").forEach { p -> FilterChip(selected=target==p,onClick={target=p},label={Text(p)}) }
                }
                Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) {
                    listOf("Cinematic","Realistic","Anime","Neon").forEach { p -> FilterChip(selected=style==p,onClick={style=p},label={Text(p)}) }
                }
                Button(onClick={generated=true}, Modifier.fillMaxWidth().height(54.dp), shape=RoundedCornerShape(18.dp)) { Text("✦  Generate Wallpaper", fontSize=16.sp) }
                if (generated) Card(Modifier.fillMaxWidth().weight(1f), shape=RoundedCornerShape(24.dp)) {
                    Box(Modifier.fillMaxSize().background(Accent.copy(alpha=.12f)), contentAlignment=Alignment.Center) {
                        Column(horizontalAlignment=Alignment.CenterHorizontally) { Text("Generation ready", fontSize=22.sp, fontWeight=FontWeight.Bold); Text("$target • $style", color=Color.LightGray); Text("AI image provider will render the final wallpaper.", color=Color.Gray) }
                    }
                } else Spacer(Modifier.weight(1f))
                Text("WallPro-AI • v0.1 • Pixel 10 optimized", color=Color.Gray, fontSize=12.sp)
            }
        }
    }
}
